#!/usr/bin/env python3
"""Copy the header and footer styles of contensi.com into the blog theme.

The main site is generated elsewhere, so its stylesheet is fetched live and
filtered down to the rules for the shared chrome (header, navigation, search
dialog, footer). Run it again whenever the main site's header changes.
"""
import re
import sys
import urllib.request
from pathlib import Path

SITE = "https://contensi.com/assets/"
ROOT = Path(__file__).resolve().parent.parent
THEME = ROOT / "themes" / "contensi"
CSS_OUT = THEME / "assets" / "css" / "site-chrome.css"
FONT_DIR = THEME / "static" / "fonts"
IMG_DIR = THEME / "assets" / "img"
FONTS = ["comfortaa.woff2", "work-sans.woff2"]
IMAGES = ["contensi-logo.png"]

CHROME = re.compile(
    r"header\.site|#kopf|\.nav-|\.logo(?![-\w])|\.logo-chip(?![\w-])|\.such-|"
    r"\.sprachumschalter|\.wrap-wide|footer\.site|\.foot-|\.social|\.slack-|"
    r"\.dlg|\.fld|\.btn(?![-\w])"
)
PAGE_SPECIFIC = re.compile(r"\.band|\.step|\.ki-nav|\.job-apply|#no-open-jobs|\.seg\b|\.foot-grid|\.foot-list")
GLOBAL = {":root", "html", "body", "html, body", "*", "[hidden]",
          "a:focus-visible, button:focus-visible"}
SCOPED = {"body:not(.p-proxmox) a": "header.site a, footer.site a, dialog a"}


def fetch(name):
    req = urllib.request.Request(SITE + name, headers={"User-Agent": "contensi-blog-vendor/1.0"})
    with urllib.request.urlopen(req) as r:
        return r.read()


def strip_comments(css):
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def blocks(css):
    i, n = 0, len(css)
    while i < n:
        start = css.find("{", i)
        if start == -1:
            return
        prelude = css[i:start].strip()
        depth, j = 1, start + 1
        while depth:
            if css[j] == "{":
                depth += 1
            elif css[j] == "}":
                depth -= 1
            j += 1
        yield prelude, css[start + 1:j - 1]
        i = j


def keep_rule(prelude):
    selector = " ".join(prelude.split())
    if selector in GLOBAL:
        return True
    if "body:not(" in selector and not CHROME.search(selector.split(")")[-1]):
        return False
    parts = selector.split(",")
    return all(CHROME.search(s) and not PAGE_SPECIFIC.search(s) for s in parts)


def filter_css(css, depth=0):
    out = []
    for prelude, body in blocks(css):
        if prelude.startswith("@font-face"):
            out.append(f"{prelude} {{{body}}}")
        elif prelude.startswith("@media") or prelude.startswith("@supports"):
            inner = filter_css(body, depth + 1)
            if inner.strip():
                out.append(f"{prelude} {{\n{inner}\n}}")
        elif prelude.startswith("@keyframes"):
            continue
        elif " ".join(prelude.split()) in SCOPED:
            out.append(f"{SCOPED[' '.join(prelude.split())]} {{{' '.join(body.split())}}}")
        elif keep_rule(prelude):
            out.append(f"{' '.join(prelude.split())} {{{' '.join(body.split())}}}")
    return "\n".join(out)


def main():
    css = strip_comments(fetch("site.css").decode("utf-8"))
    css = css.replace("url(fonts/", "url(../fonts/").replace("url(img/", "url(../img/")
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CSS_OUT.write_text(
        "/* Generated by scripts/vendor_site_css.py from https://contensi.com/assets/site.css */\n"
        + filter_css(css) + "\n"
    )
    for target, names, sub in ((FONT_DIR, FONTS, "fonts/"), (IMG_DIR, IMAGES, "img/")):
        target.mkdir(parents=True, exist_ok=True)
        for name in names:
            (target / name).write_bytes(fetch(sub + name))
    print(f"wrote {CSS_OUT.relative_to(ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
